export const ENDPOINTS = {
  LOGIN: '/auth/login',
  SIGNUP: '/auth/signup',
  FORGOT_PASSWORD: '/auth/forgot-password',
  RESET_PASSWORD: '/auth/reset-password',
  VERIFY_FORGET_PASSWORD_OTP: '/auth/verify-otp',
  SEND_VERIFICATION: '/auth/send-verification',
  UPDATE_PROFILE: '/users/profile',
  DELETE_ACCOUNT: '/users/account',
  LOGIN_WITH_GOOGLE: '/auth/google',
  LOGIN_WITH_GOOGLE_MOBILE: '/auth/google/mobile',
  SELECT_LANG: '/users/settings/language',
  GET_USER_PROFILE: '/users',
  GET_ALL_PRODUCT: '/products',
  GET_ALL_STORE: '/stores',
  GENERATE_AVATAR: '/avatars',
  GET_AVATAR: '/avatars',
  VIRTUAL_TRYON: '/virtual-tryon',
  VIRTUAL_TRYON_OUTFIT: '/virtual-tryon/outfit',
  LATEST_TRYON: '/users/latest-tryon',
  ANALYZE: '/analyze',
  SAVETOWARDROBE: '/wardrobe/from-analysis',
  WARDROBE: '/wardrobe',
  GET_PRODUCT: '/products/${id}',
  GET_ALL_STORE: '/stores',
  MATCHES: '/matches',
  MATCHES_ANALYSIS: '/matches/analysis',
  GET_FAVORITES: '/users/favorites',
  ADD_FAVORITE: '/users/favorites',
  REMOVE_FAVORITE: '/users/favorites',
  RECOMMENDATIONS:"/recommendations",
};
